/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    cuentas: CuentaAuthOperations;
  };
  blocks: {};
  collections: {
    paginas: Pagina;
    personas: Persona;
    clientes: Cliente;
    testimonios: Testimonio;
    categorias: Categoria;
    servicios: Servicio;
    casos: Caso;
    bioindicadores: Bioindicadore;
    'solicitudes-consulting': SolicitudesConsulting;
    cursos: Curso;
    objetivos: Objetivo;
    convocatorias: Convocatoria;
    inscripciones: Inscripcione;
    partners: Partner;
    tecnologias: Tecnologia;
    articulos: Articulo;
    'newsletter-ediciones': NewsletterEdicione;
    suscriptores: Suscriptore;
    proyectos: Proyecto;
    publicaciones: Publicacione;
    media: Media;
    users: User;
    cuentas: Cuenta;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    personas: PersonasSelect<false> | PersonasSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    testimonios: TestimoniosSelect<false> | TestimoniosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    servicios: ServiciosSelect<false> | ServiciosSelect<true>;
    casos: CasosSelect<false> | CasosSelect<true>;
    bioindicadores: BioindicadoresSelect<false> | BioindicadoresSelect<true>;
    'solicitudes-consulting': SolicitudesConsultingSelect<false> | SolicitudesConsultingSelect<true>;
    cursos: CursosSelect<false> | CursosSelect<true>;
    objetivos: ObjetivosSelect<false> | ObjetivosSelect<true>;
    convocatorias: ConvocatoriasSelect<false> | ConvocatoriasSelect<true>;
    inscripciones: InscripcionesSelect<false> | InscripcionesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    tecnologias: TecnologiasSelect<false> | TecnologiasSelect<true>;
    articulos: ArticulosSelect<false> | ArticulosSelect<true>;
    'newsletter-ediciones': NewsletterEdicionesSelect<false> | NewsletterEdicionesSelect<true>;
    suscriptores: SuscriptoresSelect<false> | SuscriptoresSelect<true>;
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    publicaciones: PublicacionesSelect<false> | PublicacionesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    cuentas: CuentasSelect<false> | CuentasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'configuracion-sitio': ConfiguracionSitio;
    navegacion: Navegacion;
  };
  globalsSelect: {
    'configuracion-sitio': ConfiguracionSitioSelect<false> | ConfiguracionSitioSelect<true>;
    navegacion: NavegacionSelect<false> | NavegacionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Cuenta;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CuentaAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: string;
  titulo: string;
  bloques?:
    | (
        | {
            /**
             * Linea corta sobre el titulo. Texto libre: la razon social canonica esta en Configuracion del sitio.
             */
            antetitulo?: string | null;
            titulo: string;
            bajada?: string | null;
            imagenFondo?: (string | null) | Media;
            /**
             * Ilustracion animada a la derecha del texto (solo en pantallas grandes).
             */
            adorno?: ('ninguno' | 'esquema' | 'causaRaiz') | null;
            acciones?:
              | {
                  texto: string;
                  enlace: string;
                  estilo?: ('primario' | 'secundario') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            titulo?: string | null;
            bajada?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'proceso';
          }
        | {
            /**
             * Linea corta sobre el nombre, en mayusculas. Ej: FUNDADOR Y CONSULTOR PRINCIPAL.
             */
            antetitulo?: string | null;
            nombre: string;
            /**
             * Cargo o titulo profesional.
             */
            subtitulo?: string | null;
            texto?: string | null;
            foto?: (string | null) | Media;
            acciones?:
              | {
                  texto: string;
                  enlace: string;
                  estilo?: ('primario' | 'secundario') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Se muestran sobre la foto. Ej: EXPERIENCIA / 20+ anios.
             */
            estadisticas?:
              | {
                  etiqueta: string;
                  valor: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'perfil';
          }
        | {
            texto: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contenido';
          }
        | {
            titulo?: string | null;
            origen: 'servicios' | 'cursos' | 'convocatorias' | 'tecnologias' | 'articulos' | 'casos' | 'proyectos';
            /**
             * Cuantos mostrar si la seleccion es automatica.
             */
            cantidad?: number | null;
            /**
             * Si se activa, elegis los documentos uno a uno.
             */
            seleccionManual?: boolean | null;
            documentos?:
              | (
                  | {
                      relationTo: 'servicios';
                      value: string | Servicio;
                    }
                  | {
                      relationTo: 'cursos';
                      value: string | Curso;
                    }
                  | {
                      relationTo: 'convocatorias';
                      value: string | Convocatoria;
                    }
                  | {
                      relationTo: 'tecnologias';
                      value: string | Tecnologia;
                    }
                  | {
                      relationTo: 'articulos';
                      value: string | Articulo;
                    }
                  | {
                      relationTo: 'casos';
                      value: string | Caso;
                    }
                  | {
                      relationTo: 'proyectos';
                      value: string | Proyecto;
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'destacados';
          }
        | {
            titulo?: string | null;
            bajada?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bioindicadores';
          }
        | {
            titulo?: string | null;
            bajada?: string | null;
            /**
             * El icono y el enlace salen de la unidad; aca solo se escribe la descripcion.
             */
            tarjetas?:
              | {
                  unidad: 'consulting' | 'academy' | 'technologies' | 'insights' | 'rnd';
                  descripcion: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'unidades';
          }
        | {
            titulo?: string | null;
            bajada?: string | null;
            /**
             * Exactamente cuatro: la grilla es un bento 2-1-1-2 y el ancho de cada tarjeta sale de su posicion, no se elige.
             */
            pilares?:
              | {
                  titulo: string;
                  descripcion: string;
                  icono:
                    'lupa' | 'birrete' | 'chip' | 'documento' | 'matraz' | 'molecula' | 'ajustes' | 'grafico' | 'casco';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'propuesta';
          }
        | {
            titulo?: string | null;
            bajada?: string | null;
            /**
             * Linea corta sobre el titulo, en mayusculas. Ej: PRESENCIA INDUSTRIAL.
             */
            antetitulo?: string | null;
            paises?:
              | {
                  pais: string;
                  plantas?:
                    | {
                        nombre: string;
                        descripcion: string;
                        /**
                         * Resalta la tarjeta con un acento.
                         */
                        insignia?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'presencia';
          }
        | {
            titulo: string;
            texto?: string | null;
            textoBoton: string;
            enlace: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            titulo?: string | null;
            clientes?: (string | Cliente)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logos';
          }
        | {
            titulo?: string | null;
            preguntas?:
              | {
                  pregunta: string;
                  respuesta: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            titulo?: string | null;
            personas?: (string | Persona)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'equipo';
          }
      )[]
    | null;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  /**
   * Linea de negocio a la que pertenece este contenido.
   */
  unidad?: ('consulting' | 'academy' | 'technologies' | 'insights' | 'rnd') | null;
  /**
   * Opcional. Si lo dejas vacio se usa el titulo y el resumen del documento.
   */
  seo?: {
    /**
     * Ideal hasta 60 caracteres.
     */
    titulo?: string | null;
    /**
     * Ideal hasta 160 caracteres.
     */
    descripcion?: string | null;
    imagen?: (string | null) | Media;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imagenes y documentos. El texto alternativo es obligatorio por accesibilidad.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe la imagen para lectores de pantalla y buscadores.
   */
  alt: string;
  /**
   * Opcional. Se muestra debajo de la imagen.
   */
  epigrafe?: string | null;
  credito?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios".
 */
export interface Servicio {
  id: string;
  titulo: string;
  resumen: string;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  entregables?:
    | {
        entregable: string;
        id?: string | null;
      }[]
    | null;
  beneficios?:
    | {
        beneficio: string;
        id?: string | null;
      }[]
    | null;
  dirigidoA?: string | null;
  tipo?: ('asesoria' | 'auditoria' | 'diagnostico' | 'implementacion' | 'acompanamiento') | null;
  /**
   * Linea de negocio a la que pertenece este contenido.
   */
  unidad: 'consulting' | 'academy' | 'technologies' | 'insights' | 'rnd';
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  imagenDestacada?: (string | null) | Media;
  categorias?: (string | Categoria)[] | null;
  /**
   * Menor numero aparece primero.
   */
  orden?: number | null;
  /**
   * Opcional. Si lo dejas vacio se usa el titulo y el resumen del documento.
   */
  seo?: {
    /**
     * Ideal hasta 60 caracteres.
     */
    titulo?: string | null;
    /**
     * Ideal hasta 160 caracteres.
     */
    descripcion?: string | null;
    imagen?: (string | null) | Media;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: string;
  titulo: string;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  descripcion?: string | null;
  /**
   * Puede pertenecer a mas de una linea de negocio.
   */
  unidades?: ('consulting' | 'academy' | 'technologies' | 'insights' | 'rnd')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * El programa del curso. Las fechas y precios van en Convocatorias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursos".
 */
export interface Curso {
  id: string;
  titulo: string;
  /**
   * Un parrafo. Se usa en listados y tarjetas.
   */
  resumen: string;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Perfil del participante ideal.
   */
  dirigidoA?: string | null;
  requisitos?: string | null;
  modulos?:
    | {
        titulo: string;
        detalle?: string | null;
        horas?: number | null;
        /**
         * Que objetivos de aprendizaje cubre este modulo. Puede ser mas de uno. Guarda el curso primero si la lista sale vacia.
         */
        objetivos?: (string | Objetivo)[] | null;
        id?: string | null;
      }[]
    | null;
  duracionHoras: number;
  nivel?: ('introductorio' | 'intermedio' | 'avanzado') | null;
  modalidadesDisponibles?: ('presencial' | 'online_vivo' | 'elearning' | 'mixta' | 'incompany')[] | null;
  certificacion?: string | null;
  materialIncluido?: string | null;
  /**
   * Solo si el curso esta acreditado ante SENCE. Aplica a Chile.
   */
  sence?: {
    acreditado?: boolean | null;
    codigoSence?: string | null;
    horasSence?: number | null;
  };
  /**
   * Opcional. Si lo dejas vacio se usa el titulo y el resumen del documento.
   */
  seo?: {
    /**
     * Ideal hasta 60 caracteres.
     */
    titulo?: string | null;
    /**
     * Ideal hasta 160 caracteres.
     */
    descripcion?: string | null;
    imagen?: (string | null) | Media;
    noIndexar?: boolean | null;
  };
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  /**
   * Ej: ACAD-001. Para uso administrativo.
   */
  codigo?: string | null;
  /**
   * Estado comercial del producto. No confundir con publicado/borrador.
   */
  estadoProducto: 'en_desarrollo' | 'activo' | 'discontinuado';
  imagenDestacada?: (string | null) | Media;
  categorias?: (string | Categoria)[] | null;
  /**
   * Quien suele dictarlo. El relator de cada fecha se define en la convocatoria.
   */
  relatoresHabituales?: (string | Persona)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Objetivos de aprendizaje de un curso. Los modulos se marcan a estos desde el curso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objetivos".
 */
export interface Objetivo {
  id: string;
  curso: string | Curso;
  /**
   * El objetivo de aprendizaje, en una frase.
   */
  objetivo: string;
  /**
   * Link a un video corto (YouTube, Vimeo, Loom) que presenta este objetivo. Opcional.
   */
  videoIntro?: string | null;
  /**
   * Menor numero aparece primero.
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Equipo, relatores y autores. La misma persona puede cumplir varios roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas".
 */
export interface Persona {
  id: string;
  nombre: string;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  roles: ('equipo' | 'relator' | 'autor' | 'investigador' | 'externo')[];
  cargo?: string | null;
  bio?: string | null;
  foto?: (string | null) | Media;
  email?: string | null;
  linkedin?: string | null;
  visibleEnSitio?: boolean | null;
  /**
   * Menor numero aparece primero.
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cada fecha en que se dicta un curso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convocatorias".
 */
export interface Convocatoria {
  id: string;
  /**
   * El programa se hereda de aqui. No lo repitas.
   */
  curso: string | Curso;
  /**
   * Ej: "Auditoria de procesos acuicolas — Puerto Montt, marzo 2026".
   */
  titulo: string;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  fechaInicio: string;
  fechaTermino?: string | null;
  /**
   * Solo si el curso se dicta en varias jornadas separadas.
   */
  sesiones?:
    | {
        fecha: string;
        duracionHoras?: number | null;
        tema?: string | null;
        id?: string | null;
      }[]
    | null;
  modalidad: 'presencial' | 'online_vivo' | 'elearning' | 'mixta' | 'incompany';
  lugar?: {
    ciudad?: string | null;
    region?: string | null;
    direccion?: string | null;
    sede?: string | null;
    plataforma?: string | null;
  };
  relatores?: (string | Persona)[] | null;
  valor: {
    monto?: number | null;
    moneda?: ('CLP' | 'UF' | 'USD') | null;
    /**
     * En B2B chileno lo habitual es cotizar neto y agregar IVA.
     */
    montoEsNeto?: boolean | null;
    aplicaFranquiciaSence?: boolean | null;
    cupoMaximo: number;
    cupoMinimo?: number | null;
    inscripcionDesde?: string | null;
    inscripcionHasta?: string | null;
  };
  /**
   * Calculado desde Inscripciones. Visible al abrir la convocatoria.
   */
  inscritosConfirmados?: number | null;
  /**
   * Estado operativo. Solo "inscripciones abiertas" admite nuevas inscripciones.
   */
  estadoConvocatoria:
    'planificada' | 'inscripciones_abiertas' | 'cupo_completo' | 'en_curso' | 'finalizada' | 'cancelada';
  notasInternas?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tecnologias".
 */
export interface Tecnologia {
  id: string;
  titulo: string;
  resumen: string;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  partner: string | Partner;
  aplicaciones?:
    | {
        aplicacion: string;
        id?: string | null;
      }[]
    | null;
  especificaciones?:
    | {
        parametro: string;
        valor: string;
        id?: string | null;
      }[]
    | null;
  fichaTecnica?: (string | null) | Media;
  galeria?:
    | {
        imagen: string | Media;
        id?: string | null;
      }[]
    | null;
  estadoRepresentacion: 'vigente' | 'evaluacion' | 'descontinuada';
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  imagenDestacada?: (string | null) | Media;
  categorias?: (string | Categoria)[] | null;
  /**
   * Opcional. Si lo dejas vacio se usa el titulo y el resumen del documento.
   */
  seo?: {
    /**
     * Ideal hasta 60 caracteres.
     */
    titulo?: string | null;
    /**
     * Ideal hasta 160 caracteres.
     */
    descripcion?: string | null;
    imagen?: (string | null) | Media;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * La marca o fabricante. Sus productos van en Tecnologias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  nombre: string;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (string | null) | Media;
  sitioWeb?: string | null;
  pais?: string | null;
  tipoRepresentacion?: ('exclusiva' | 'distribuidor' | 'alianza') | null;
  vigenteDesde?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos".
 */
export interface Articulo {
  id: string;
  titulo: string;
  bajada: string;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tipo: 'articulo' | 'analisis' | 'linkedin' | 'noticia' | 'caso_comentado';
  /**
   * Fecha que se muestra. Para publicar a futuro usa "programar publicacion".
   */
  fechaPublicacion: string;
  /**
   * Aparece grande al inicio de /insights. Si hay varios, se muestra el mas reciente.
   */
  destacado?: boolean | null;
  /**
   * Sigue accesible por URL pero se oculta de los listados. Evita romper enlaces.
   */
  archivado?: boolean | null;
  autores?: (string | Persona)[] | null;
  urlLinkedin?: string | null;
  /**
   * Puede pertenecer a mas de una linea de negocio.
   */
  unidades?: ('consulting' | 'academy' | 'technologies' | 'insights' | 'rnd')[] | null;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  imagenDestacada?: (string | null) | Media;
  categorias?: (string | Categoria)[] | null;
  tiempoLecturaMinutos?: number | null;
  /**
   * Opcional. Si lo dejas vacio se usa el titulo y el resumen del documento.
   */
  seo?: {
    /**
     * Ideal hasta 60 caracteres.
     */
    titulo?: string | null;
    /**
     * Ideal hasta 160 caracteres.
     */
    descripcion?: string | null;
    imagen?: (string | null) | Media;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos".
 */
export interface Caso {
  id: string;
  titulo: string;
  resumen: string;
  desafio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solucion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  resultados?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cifras concretas. Es lo que mas convence en un caso.
   */
  metricas?:
    | {
        /**
         * Ej: "-32%"
         */
        valor: string;
        /**
         * Ej: "consumo de agua"
         */
        descripcion: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Para trabajos bajo confidencialidad.
   */
  clienteAnonimo?: boolean | null;
  cliente?: (string | null) | Cliente;
  /**
   * Ej: "salmonicultora de la Region de Los Lagos".
   */
  descripcionClienteAnonimo?: string | null;
  /**
   * Puede pertenecer a mas de una linea de negocio.
   */
  unidades?: ('consulting' | 'academy' | 'technologies' | 'insights' | 'rnd')[] | null;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  imagenDestacada?: (string | null) | Media;
  categorias?: (string | Categoria)[] | null;
  servicios?: (string | Servicio)[] | null;
  /**
   * Opcional. Si lo dejas vacio se usa el titulo y el resumen del documento.
   */
  seo?: {
    /**
     * Ideal hasta 60 caracteres.
     */
    titulo?: string | null;
    /**
     * Ideal hasta 160 caracteres.
     */
    descripcion?: string | null;
    imagen?: (string | null) | Media;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Empresas atendidas. Solo se muestran publicamente las autorizadas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: string;
  nombre: string;
  logo?: (string | null) | Media;
  sitioWeb?: string | null;
  rubro?: ('acuicultura' | 'pesca' | 'alimentos' | 'aguas' | 'publico' | 'academia' | 'otro') | null;
  mostrarLogo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: string;
  titulo: string;
  resumen: string;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objetivos?:
    | {
        objetivo: string;
        id?: string | null;
      }[]
    | null;
  resultados?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tipo?: ('investigacion' | 'piloto' | 'poc' | 'desarrollo') | null;
  estadoProyecto: 'formulacion' | 'en_curso' | 'finalizado' | 'confidencial' | 'suspendido';
  anioInicio?: number | null;
  anioTermino?: number | null;
  financiamiento?: {
    /**
     * Ej: CORFO, ANID, FIA, privado.
     */
    fuente?: string | null;
    codigoProyecto?: string | null;
  };
  contrapartes?:
    | {
        nombre: string;
        tipo?: ('universidad' | 'centro' | 'empresa' | 'publico') | null;
        logo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  equipo?: (string | Persona)[] | null;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  imagenDestacada?: (string | null) | Media;
  categorias?: (string | Categoria)[] | null;
  /**
   * Opcional. Si lo dejas vacio se usa el titulo y el resumen del documento.
   */
  seo?: {
    /**
     * Ideal hasta 60 caracteres.
     */
    titulo?: string | null;
    /**
     * Ideal hasta 160 caracteres.
     */
    descripcion?: string | null;
    imagen?: (string | null) | Media;
    noIndexar?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios".
 */
export interface Testimonio {
  id: string;
  cita: string;
  autorNombre: string;
  autorCargo?: string | null;
  autorEmpresa?: string | null;
  cliente?: (string | null) | Cliente;
  foto?: (string | null) | Media;
  /**
   * Linea de negocio a la que pertenece este contenido.
   */
  unidad?: ('consulting' | 'academy' | 'technologies' | 'insights' | 'rnd') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Organismos de la microscopia de lodos activados y que indica cada uno sobre la planta.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bioindicadores".
 */
export interface Bioindicadore {
  id: string;
  /**
   * Nombre comun. Ej: Ciliados pedunculados.
   */
  nombre: string;
  /**
   * Genero o grupo. Ej: Opercularia sp.
   */
  nombreCientifico?: string | null;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  /**
   * Microscopia del organismo. La descripcion accesible va en el propio archivo.
   */
  imagen: string | Media;
  grupo: 'floculo' | 'ciliado' | 'ameba' | 'metazoo' | 'filamentosa';
  /**
   * Que senala su presencia (o su exceso) para la operacion.
   */
  condicion: 'buena' | 'alerta' | 'problema';
  /**
   * Interpretacion operacional, 1 a 3 frases.
   */
  queIndica: string;
  /**
   * Orden de aparicion en la galeria (menor primero).
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pedidos de contacto de cuentas. No se exponen publicamente salvo a su dueño.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solicitudes-consulting".
 */
export interface SolicitudesConsulting {
  id: string;
  cuenta: string | Cuenta;
  /**
   * Opcional. Si el interes es en un servicio puntual.
   */
  servicio?: (string | null) | Servicio;
  empresa?: string | null;
  mensaje: string;
  estado: 'nueva' | 'contactada' | 'cotizando' | 'ganada' | 'perdida';
  notasInternas?: string | null;
  sitioWebContacto?: string | null;
  huellaOrigen?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuentas".
 */
export interface Cuenta {
  id: string;
  nombre: string;
  telefono?: string | null;
  rut?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cuentas';
}
/**
 * Datos personales. No se exponen publicamente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscripciones".
 */
export interface Inscripcione {
  id: string;
  /**
   * Quien gestiona la inscripcion. Puede no ser quien asiste (ver pestaña Participante).
   */
  cuenta: string | Cuenta;
  convocatoria: string | Convocatoria;
  participanteNombre: string;
  participanteEmail: string;
  participanteTelefono?: string | null;
  /**
   * Necesario si requiere factura o franquicia SENCE.
   */
  participanteRut?: string | null;
  participanteCargo?: string | null;
  participanteEmpresa?: string | null;
  pago: {
    estadoPago: 'pendiente' | 'pagado' | 'parcial' | 'reembolsado' | 'sin_costo';
    medioPago?: ('transferencia' | 'webpay' | 'flow' | 'stripe' | 'orden_compra' | 'sence' | 'otro') | null;
    montoPagado?: number | null;
    moneda?: ('CLP' | 'UF' | 'USD') | null;
    fechaPago?: string | null;
    /**
     * Lo escribira el webhook de la pasarela. Indexado para conciliar pagos.
     */
    referenciaExterna?: string | null;
  };
  requiereFactura?: boolean | null;
  facturacion?: {
    razonSocial?: string | null;
    rut?: string | null;
    giro?: string | null;
    direccion?: string | null;
    comuna?: string | null;
    emailFacturacion?: string | null;
    ordenCompra?: string | null;
  };
  estadoInscripcion: 'pendiente' | 'confirmada' | 'lista_espera' | 'asistio' | 'no_asistio' | 'cancelada';
  origen?: ('web' | 'linkedin' | 'newsletter' | 'referido' | 'directo') | null;
  notasInternas?: string | null;
  sitioWebContacto?: string | null;
  huellaOrigen?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-ediciones".
 */
export interface NewsletterEdicione {
  id: string;
  numero: number;
  titulo: string;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  /**
   * Lo que se ve en la bandeja de entrada. Corto funciona mejor.
   */
  asunto: string;
  /**
   * Texto de vista previa, despues del asunto.
   */
  preheader?: string | null;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Articulos del sitio que se referencian en esta edicion.
   */
  articulosDestacados?: (string | Articulo)[] | null;
  /**
   * Vacio = va a todos los suscriptores confirmados.
   */
  segmentacion?: ('consulting' | 'academy' | 'technologies' | 'insights' | 'rnd')[] | null;
  /**
   * "Enviada" es irreversible: el contenido queda congelado.
   */
  estadoEnvio: 'borrador' | 'programada' | 'enviada' | 'cancelada';
  fechaProgramada?: string | null;
  /**
   * Lo escribe el proceso de envio.
   */
  fechaEnvio?: string | null;
  /**
   * Cantidad a la que se envio.
   */
  destinatarios?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Datos personales. No se exponen publicamente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suscriptores".
 */
export interface Suscriptore {
  id: string;
  email: string;
  nombre?: string | null;
  empresa?: string | null;
  cargo?: string | null;
  estado: 'pendiente_confirmacion' | 'confirmado' | 'baja' | 'rebotado';
  /**
   * Permite segmentar los envios.
   */
  intereses?: ('consulting' | 'academy' | 'technologies' | 'insights' | 'rnd')[] | null;
  /**
   * Prueba de aceptacion. No editar a mano salvo correccion justificada.
   */
  consentimiento?: {
    aceptado?: boolean | null;
    fechaAceptacion?: string | null;
    ip?: string | null;
    /**
     * Se guarda una copia literal, no una referencia.
     */
    textoAceptado?: string | null;
    versionPolitica?: string | null;
  };
  tokenConfirmacion?: string | null;
  fechaConfirmacion?: string | null;
  fechaBaja?: string | null;
  origen?: ('web' | 'linkedin' | 'evento' | 'manual') | null;
  sitioWebContacto?: string | null;
  huellaOrigen?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicaciones".
 */
export interface Publicacione {
  id: string;
  titulo: string;
  /**
   * URL del contenido. Se genera solo desde el titulo; cambiarlo rompe enlaces existentes.
   */
  slug?: string | null;
  abstract?: string | null;
  tipo: 'paper' | 'capitulo' | 'ponencia' | 'informe' | 'tesis';
  anio: number;
  revista?: string | null;
  doi?: string | null;
  url?: string | null;
  indexacion?: ('wos' | 'scopus' | 'scielo' | 'latindex')[] | null;
  /**
   * Tal como aparece en la publicacion, incluyendo autores externos.
   */
  autoresTexto?: string | null;
  /**
   * Para enlazar con las fichas del equipo.
   */
  autoresInternos?: (string | Persona)[] | null;
  proyecto?: (string | null) | Proyecto;
  archivo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  nombre: string;
  /**
   * El editor gestiona contenido pero no usuarios ni configuracion del sitio.
   */
  rol: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'paginas';
        value: string | Pagina;
      } | null)
    | ({
        relationTo: 'personas';
        value: string | Persona;
      } | null)
    | ({
        relationTo: 'clientes';
        value: string | Cliente;
      } | null)
    | ({
        relationTo: 'testimonios';
        value: string | Testimonio;
      } | null)
    | ({
        relationTo: 'categorias';
        value: string | Categoria;
      } | null)
    | ({
        relationTo: 'servicios';
        value: string | Servicio;
      } | null)
    | ({
        relationTo: 'casos';
        value: string | Caso;
      } | null)
    | ({
        relationTo: 'bioindicadores';
        value: string | Bioindicadore;
      } | null)
    | ({
        relationTo: 'solicitudes-consulting';
        value: string | SolicitudesConsulting;
      } | null)
    | ({
        relationTo: 'cursos';
        value: string | Curso;
      } | null)
    | ({
        relationTo: 'objetivos';
        value: string | Objetivo;
      } | null)
    | ({
        relationTo: 'convocatorias';
        value: string | Convocatoria;
      } | null)
    | ({
        relationTo: 'inscripciones';
        value: string | Inscripcione;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'tecnologias';
        value: string | Tecnologia;
      } | null)
    | ({
        relationTo: 'articulos';
        value: string | Articulo;
      } | null)
    | ({
        relationTo: 'newsletter-ediciones';
        value: string | NewsletterEdicione;
      } | null)
    | ({
        relationTo: 'suscriptores';
        value: string | Suscriptore;
      } | null)
    | ({
        relationTo: 'proyectos';
        value: string | Proyecto;
      } | null)
    | ({
        relationTo: 'publicaciones';
        value: string | Publicacione;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'cuentas';
        value: string | Cuenta;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'cuentas';
        value: string | Cuenta;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'cuentas';
        value: string | Cuenta;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  bloques?:
    | T
    | {
        hero?:
          | T
          | {
              antetitulo?: T;
              titulo?: T;
              bajada?: T;
              imagenFondo?: T;
              adorno?: T;
              acciones?:
                | T
                | {
                    texto?: T;
                    enlace?: T;
                    estilo?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        proceso?:
          | T
          | {
              titulo?: T;
              bajada?: T;
              id?: T;
              blockName?: T;
            };
        perfil?:
          | T
          | {
              antetitulo?: T;
              nombre?: T;
              subtitulo?: T;
              texto?: T;
              foto?: T;
              acciones?:
                | T
                | {
                    texto?: T;
                    enlace?: T;
                    estilo?: T;
                    id?: T;
                  };
              estadisticas?:
                | T
                | {
                    etiqueta?: T;
                    valor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contenido?:
          | T
          | {
              texto?: T;
              id?: T;
              blockName?: T;
            };
        destacados?:
          | T
          | {
              titulo?: T;
              origen?: T;
              cantidad?: T;
              seleccionManual?: T;
              documentos?: T;
              id?: T;
              blockName?: T;
            };
        bioindicadores?:
          | T
          | {
              titulo?: T;
              bajada?: T;
              id?: T;
              blockName?: T;
            };
        unidades?:
          | T
          | {
              titulo?: T;
              bajada?: T;
              tarjetas?:
                | T
                | {
                    unidad?: T;
                    descripcion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        propuesta?:
          | T
          | {
              titulo?: T;
              bajada?: T;
              pilares?:
                | T
                | {
                    titulo?: T;
                    descripcion?: T;
                    icono?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        presencia?:
          | T
          | {
              titulo?: T;
              bajada?: T;
              antetitulo?: T;
              paises?:
                | T
                | {
                    pais?: T;
                    plantas?:
                      | T
                      | {
                          nombre?: T;
                          descripcion?: T;
                          insignia?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              titulo?: T;
              texto?: T;
              textoBoton?: T;
              enlace?: T;
              id?: T;
              blockName?: T;
            };
        logos?:
          | T
          | {
              titulo?: T;
              clientes?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              titulo?: T;
              preguntas?:
                | T
                | {
                    pregunta?: T;
                    respuesta?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        equipo?:
          | T
          | {
              titulo?: T;
              personas?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  unidad?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas_select".
 */
export interface PersonasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  roles?: T;
  cargo?: T;
  bio?: T;
  foto?: T;
  email?: T;
  linkedin?: T;
  visibleEnSitio?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  nombre?: T;
  logo?: T;
  sitioWeb?: T;
  rubro?: T;
  mostrarLogo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios_select".
 */
export interface TestimoniosSelect<T extends boolean = true> {
  cita?: T;
  autorNombre?: T;
  autorCargo?: T;
  autorEmpresa?: T;
  cliente?: T;
  foto?: T;
  unidad?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descripcion?: T;
  unidades?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios_select".
 */
export interface ServiciosSelect<T extends boolean = true> {
  titulo?: T;
  resumen?: T;
  descripcion?: T;
  entregables?:
    | T
    | {
        entregable?: T;
        id?: T;
      };
  beneficios?:
    | T
    | {
        beneficio?: T;
        id?: T;
      };
  dirigidoA?: T;
  tipo?: T;
  unidad?: T;
  slug?: T;
  imagenDestacada?: T;
  categorias?: T;
  orden?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "casos_select".
 */
export interface CasosSelect<T extends boolean = true> {
  titulo?: T;
  resumen?: T;
  desafio?: T;
  solucion?: T;
  resultados?: T;
  metricas?:
    | T
    | {
        valor?: T;
        descripcion?: T;
        id?: T;
      };
  clienteAnonimo?: T;
  cliente?: T;
  descripcionClienteAnonimo?: T;
  unidades?: T;
  slug?: T;
  imagenDestacada?: T;
  categorias?: T;
  servicios?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bioindicadores_select".
 */
export interface BioindicadoresSelect<T extends boolean = true> {
  nombre?: T;
  nombreCientifico?: T;
  slug?: T;
  imagen?: T;
  grupo?: T;
  condicion?: T;
  queIndica?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solicitudes-consulting_select".
 */
export interface SolicitudesConsultingSelect<T extends boolean = true> {
  cuenta?: T;
  servicio?: T;
  empresa?: T;
  mensaje?: T;
  estado?: T;
  notasInternas?: T;
  sitioWebContacto?: T;
  huellaOrigen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursos_select".
 */
export interface CursosSelect<T extends boolean = true> {
  titulo?: T;
  resumen?: T;
  descripcion?: T;
  dirigidoA?: T;
  requisitos?: T;
  modulos?:
    | T
    | {
        titulo?: T;
        detalle?: T;
        horas?: T;
        objetivos?: T;
        id?: T;
      };
  duracionHoras?: T;
  nivel?: T;
  modalidadesDisponibles?: T;
  certificacion?: T;
  materialIncluido?: T;
  sence?:
    | T
    | {
        acreditado?: T;
        codigoSence?: T;
        horasSence?: T;
      };
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        noIndexar?: T;
      };
  slug?: T;
  codigo?: T;
  estadoProducto?: T;
  imagenDestacada?: T;
  categorias?: T;
  relatoresHabituales?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objetivos_select".
 */
export interface ObjetivosSelect<T extends boolean = true> {
  curso?: T;
  objetivo?: T;
  videoIntro?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convocatorias_select".
 */
export interface ConvocatoriasSelect<T extends boolean = true> {
  curso?: T;
  titulo?: T;
  slug?: T;
  fechaInicio?: T;
  fechaTermino?: T;
  sesiones?:
    | T
    | {
        fecha?: T;
        duracionHoras?: T;
        tema?: T;
        id?: T;
      };
  modalidad?: T;
  lugar?:
    | T
    | {
        ciudad?: T;
        region?: T;
        direccion?: T;
        sede?: T;
        plataforma?: T;
      };
  relatores?: T;
  valor?:
    | T
    | {
        monto?: T;
        moneda?: T;
        montoEsNeto?: T;
        aplicaFranquiciaSence?: T;
        cupoMaximo?: T;
        cupoMinimo?: T;
        inscripcionDesde?: T;
        inscripcionHasta?: T;
      };
  inscritosConfirmados?: T;
  estadoConvocatoria?: T;
  notasInternas?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscripciones_select".
 */
export interface InscripcionesSelect<T extends boolean = true> {
  cuenta?: T;
  convocatoria?: T;
  participanteNombre?: T;
  participanteEmail?: T;
  participanteTelefono?: T;
  participanteRut?: T;
  participanteCargo?: T;
  participanteEmpresa?: T;
  pago?:
    | T
    | {
        estadoPago?: T;
        medioPago?: T;
        montoPagado?: T;
        moneda?: T;
        fechaPago?: T;
        referenciaExterna?: T;
      };
  requiereFactura?: T;
  facturacion?:
    | T
    | {
        razonSocial?: T;
        rut?: T;
        giro?: T;
        direccion?: T;
        comuna?: T;
        emailFacturacion?: T;
        ordenCompra?: T;
      };
  estadoInscripcion?: T;
  origen?: T;
  notasInternas?: T;
  sitioWebContacto?: T;
  huellaOrigen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  logo?: T;
  sitioWeb?: T;
  pais?: T;
  tipoRepresentacion?: T;
  vigenteDesde?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tecnologias_select".
 */
export interface TecnologiasSelect<T extends boolean = true> {
  titulo?: T;
  resumen?: T;
  descripcion?: T;
  partner?: T;
  aplicaciones?:
    | T
    | {
        aplicacion?: T;
        id?: T;
      };
  especificaciones?:
    | T
    | {
        parametro?: T;
        valor?: T;
        id?: T;
      };
  fichaTecnica?: T;
  galeria?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  estadoRepresentacion?: T;
  slug?: T;
  imagenDestacada?: T;
  categorias?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articulos_select".
 */
export interface ArticulosSelect<T extends boolean = true> {
  titulo?: T;
  bajada?: T;
  contenido?: T;
  tipo?: T;
  fechaPublicacion?: T;
  destacado?: T;
  archivado?: T;
  autores?: T;
  urlLinkedin?: T;
  unidades?: T;
  slug?: T;
  imagenDestacada?: T;
  categorias?: T;
  tiempoLecturaMinutos?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-ediciones_select".
 */
export interface NewsletterEdicionesSelect<T extends boolean = true> {
  numero?: T;
  titulo?: T;
  slug?: T;
  asunto?: T;
  preheader?: T;
  contenido?: T;
  articulosDestacados?: T;
  segmentacion?: T;
  estadoEnvio?: T;
  fechaProgramada?: T;
  fechaEnvio?: T;
  destinatarios?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suscriptores_select".
 */
export interface SuscriptoresSelect<T extends boolean = true> {
  email?: T;
  nombre?: T;
  empresa?: T;
  cargo?: T;
  estado?: T;
  intereses?: T;
  consentimiento?:
    | T
    | {
        aceptado?: T;
        fechaAceptacion?: T;
        ip?: T;
        textoAceptado?: T;
        versionPolitica?: T;
      };
  tokenConfirmacion?: T;
  fechaConfirmacion?: T;
  fechaBaja?: T;
  origen?: T;
  sitioWebContacto?: T;
  huellaOrigen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  titulo?: T;
  resumen?: T;
  descripcion?: T;
  objetivos?:
    | T
    | {
        objetivo?: T;
        id?: T;
      };
  resultados?: T;
  tipo?: T;
  estadoProyecto?: T;
  anioInicio?: T;
  anioTermino?: T;
  financiamiento?:
    | T
    | {
        fuente?: T;
        codigoProyecto?: T;
      };
  contrapartes?:
    | T
    | {
        nombre?: T;
        tipo?: T;
        logo?: T;
        id?: T;
      };
  equipo?: T;
  slug?: T;
  imagenDestacada?: T;
  categorias?: T;
  seo?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        imagen?: T;
        noIndexar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicaciones_select".
 */
export interface PublicacionesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  abstract?: T;
  tipo?: T;
  anio?: T;
  revista?: T;
  doi?: T;
  url?: T;
  indexacion?: T;
  autoresTexto?: T;
  autoresInternos?: T;
  proyecto?: T;
  archivo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  epigrafe?: T;
  credito?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuentas_select".
 */
export interface CuentasSelect<T extends boolean = true> {
  nombre?: T;
  telefono?: T;
  rut?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion-sitio".
 */
export interface ConfiguracionSitio {
  id: string;
  nombreComercial: string;
  /**
   * Nombre legal. Se usa en documentos y pie de pagina.
   */
  razonSocial: string;
  rut?: string | null;
  giro?: string | null;
  descripcionBreve?: string | null;
  logo?: (string | null) | Media;
  logoOscuro?: (string | null) | Media;
  favicon?: (string | null) | Media;
  email?: string | null;
  telefono?: string | null;
  direccion?: string | null;
  comuna?: string | null;
  region?: string | null;
  whatsapp?: {
    /**
     * Numero con codigo de pais, ej: +56912345678. Si se deja vacio, el boton flotante no se muestra.
     */
    numero?: string | null;
    /**
     * Mensaje precargado cuando alguien abre el boton flotante de WhatsApp.
     */
    mensajePorDefecto?: string | null;
  };
  redes?:
    | {
        plataforma: 'linkedin' | 'youtube' | 'instagram' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Se guarda junto a cada consentimiento de newsletter. Subila cuando cambies la politica.
   */
  versionPoliticaPrivacidad?: string | null;
  /**
   * Se copia literalmente en cada suscripcion como prueba de consentimiento.
   */
  textoConsentimientoNewsletter?: string | null;
  tituloPorDefecto?: string | null;
  descripcionPorDefecto?: string | null;
  imagenCompartir?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navegacion".
 */
export interface Navegacion {
  id: string;
  principal?:
    | {
        etiqueta: string;
        url: string;
        nuevaPestana?: boolean | null;
        submenu?:
          | {
              etiqueta: string;
              url: string;
              nuevaPestana?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  pie?:
    | {
        titulo: string;
        enlaces?:
          | {
              etiqueta: string;
              url: string;
              nuevaPestana?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion-sitio_select".
 */
export interface ConfiguracionSitioSelect<T extends boolean = true> {
  nombreComercial?: T;
  razonSocial?: T;
  rut?: T;
  giro?: T;
  descripcionBreve?: T;
  logo?: T;
  logoOscuro?: T;
  favicon?: T;
  email?: T;
  telefono?: T;
  direccion?: T;
  comuna?: T;
  region?: T;
  whatsapp?:
    | T
    | {
        numero?: T;
        mensajePorDefecto?: T;
      };
  redes?:
    | T
    | {
        plataforma?: T;
        url?: T;
        id?: T;
      };
  versionPoliticaPrivacidad?: T;
  textoConsentimientoNewsletter?: T;
  tituloPorDefecto?: T;
  descripcionPorDefecto?: T;
  imagenCompartir?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navegacion_select".
 */
export interface NavegacionSelect<T extends boolean = true> {
  principal?:
    | T
    | {
        etiqueta?: T;
        url?: T;
        nuevaPestana?: T;
        submenu?:
          | T
          | {
              etiqueta?: T;
              url?: T;
              nuevaPestana?: T;
              id?: T;
            };
        id?: T;
      };
  pie?:
    | T
    | {
        titulo?: T;
        enlaces?:
          | T
          | {
              etiqueta?: T;
              url?: T;
              nuevaPestana?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'paginas';
          value: string | Pagina;
        } | null)
      | ({
          relationTo: 'testimonios';
          value: string | Testimonio;
        } | null)
      | ({
          relationTo: 'servicios';
          value: string | Servicio;
        } | null)
      | ({
          relationTo: 'casos';
          value: string | Caso;
        } | null)
      | ({
          relationTo: 'bioindicadores';
          value: string | Bioindicadore;
        } | null)
      | ({
          relationTo: 'cursos';
          value: string | Curso;
        } | null)
      | ({
          relationTo: 'convocatorias';
          value: string | Convocatoria;
        } | null)
      | ({
          relationTo: 'partners';
          value: string | Partner;
        } | null)
      | ({
          relationTo: 'tecnologias';
          value: string | Tecnologia;
        } | null)
      | ({
          relationTo: 'articulos';
          value: string | Articulo;
        } | null)
      | ({
          relationTo: 'proyectos';
          value: string | Proyecto;
        } | null)
      | ({
          relationTo: 'publicaciones';
          value: string | Publicacione;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}